apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todo
  namespaceSelector:
    matchNames:
      - todo
  endpoints:
    - port: 80
      interval: 30s
