version: "1.0"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:alpine-jdk21
    networks:
      - jenkins-net
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - jenkins-docker-certs:/certs/client 
      - jenkins-data:/var/jenkins_home 
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    networks:
      - jenkins-net
    restart: unless-stopped
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    depends_on:
      - sonarqubeDb
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    
  
  sonarqubeDb:
    container_name: sonarqube_db
    image: postgres:17-alpine
    networks:
      - jenkins-net
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - sonarqube_db_data:/var/lib/postgresql/da
    
networks:
  jenkins-net:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  sonarqube_db:
  sonarqube_db_data: