AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a VPC with public and private subnets, an Internet Gateway, and a default Security Group.

Parameters:
  Name:
    Type: String
    Description: Name prefix for all resources
    Default: NT548-group23

  VPCCidrBlock: 
    Type: String
    Description: CIDR block for the VPC
    Default: 10.0.0.0/16

  PublicSubnetCidrBlock:
    Type: String
    Description: CIDR block for the public subnet 
    Default: 10.0.1.0/24
    
  PrivateSubnetCidrBlock:
    Type: String
    Description: CIDR block for the private subnet 
    Default: 10.0.2.0/24

Resources:
  # VPC 
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${Name}-vpc"

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidrBlock
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub "${Name}-pb-subnet"
        
  # Private Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidrBlock
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub "${Name}-pr-subnet"

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: !Sub "${Name}-igw" 

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Security Group 
  DefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Default Security Group for MyVPC"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: !Sub "${Name}-default-sg"

Outputs:
  VPC:
    Value: !Ref VPC
    Description: "VPC ID"
  PublicSubnetId:
    Value: !Ref PublicSubnet
    Description: "Public Subnet ID"
  PrivateSubnetId:
    Value: !Ref PrivateSubnet
    Description: "Private Subnet ID"
  InternetGatewayId:
    Value: !Ref InternetGateway
    Description: "Internet Gateway ID"
