AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a NAT Gateway

Parameters:
  Name:
    Type: String
    Description: Name prefix for all resources

  PublicSubnetId:
    Type: String
    Description: ID of the Public Subnet

Resources:
  # Elastic IP Allocation for NAT Gateway
  ElasticIPForNAT:
    Type: AWS::EC2::EIP
    Properties:
      Tags:
      - Key: Name
        Value: !Sub "${Name}-NatIP"

  # NAT Gateway Resource
  NATGatewayResource:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet
      AllocationId: !GetAtt ElasticIPForNAT.AllocationId
      Tags:
      - Key: Name
        Value: !Sub "${Name}-NatGW"

Outputs:
  NatGatewayID:
    Description: "The ID of the NAT Gateway created"
    Value: !Ref NATGatewayResource
