AWSTemplateFormatVersion: "2010-09-09"
Description: NT548 CloudFormation

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket
    Default: group23-s3

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.us-east-1.amazonaws.com/aws-vpc-with-subnets.yml

  # NAT Gateway Stack
  NATGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.us-east-1.amazonaws.com/aws-nat-gateway.yml
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId

  # Route Tables Stack
  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.us-east-1.amazonaws.com/aws-route-table.yml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPC
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        NatGatewayId: !GetAtt NATGatewayStack.Outputs.NatGatewayId

