---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-fe
  namespace: todo
  labels:
    app: todo-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-fe
  template:
    metadata:
      labels:
        app: todo-fe
    spec:
      containers:
      - name: todo-fe
        image: phuochovan/todo-fe:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-fe
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: todo-fe
  ports:
  - port: 80
    targetPort: 80
