name: "Terraform Destroy"

on:
  push:
    branches:
      - Lab
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY" to confirm destruction of infrastructure'
        required: true
        type: string
